[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Casey Mau <casey-mau@pluralsight.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pylint = "^2.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
