[tool.poetry]
name = "recursion_coding_problem"
version = "0.1.0"
description = ""
authors = ["mauza <mauza@mauza.net>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
